import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {tokenAmount,remainingAllowance,readableChanges,historyLabel} from '../core/rules-presentation';
import {rulesChanges,rulesBundleSchema,type RulesContext} from '../core/rules-protocol';
const context=()=>JSON.parse(readFileSync('work/rc20-simple/browser-context.json','utf8')) as RulesContext;
it('preserves all decimals and distinguishes an unknown amount from zero',()=>{expect(tokenAmount('100000000000000001','eth')).toBe('0.100000000000000001');expect(tokenAmount('25000001','usdg')).toBe('25.000001');expect(tokenAmount(undefined,'eth')).toBe('—');expect(tokenAmount('0','eth')).toBe('0');expect(tokenAmount((2n**128n-1n).toString(),'usdg')).toBe('340282366920938463463374607431768.211455');});
it('uses every global budget and count, saturates exhausted budgets, and never invents unknown usage',()=>{const c=context();c.rules!.eth={perPayment:'10',rolling:'100',sevenDay:'200',thirtyDay:'300',approvalAbove:'5',count:20};expect(remainingAllowance(c,undefined,'eth')).toBeUndefined();expect(remainingAllowance(c,['30','1','190','250'],'eth')).toBe('10');expect(remainingAllowance(c,['101','1','0','0'],'eth')).toBe('0');expect(remainingAllowance(c,['0','20','0','0'],'eth')).toBe('0');c.paused=true;expect(remainingAllowance(c,['0','0','0','0'],'eth')).toBe('0');c.paused=false;c.rules!.expires=1;expect(remainingAllowance(c,undefined,'eth')).toBeUndefined();expect(remainingAllowance(c,['0','0','0','0'],'eth')).toBe('0');});
it('renders every validated change including removed recipients, role changes and wider schedules without raw masks or base-unit amounts',()=>{const before=context().rules!;const after=structuredClone(before);after.eth.perPayment='200000000000000001';after.weekdays=21;after.categories=3;after.startMinute=540;after.endMinute=1020;after.agent='0x'+'12'.repeat(20);after.recipients=[];rulesBundleSchema.parse(after);const changes=readableChanges(before,after);expect(changes).toHaveLength(rulesChanges(before,after).length);expect(changes.find(c=>c.field==='eth.perPayment')?.afterText).toBe('0.200000000000000001 ETH');expect(changes.find(c=>c.field==='weekdays')?.afterText).toBe('Monday, Wednesday, Friday');expect(changes.find(c=>c.field==='categories')?.afterText).toBe('General, Software');expect(changes.find(c=>c.field==='startMinute')?.afterText).toBe('09:00');expect(changes.find(c=>c.field==='recipients.0')?.beforeText).toContain(before.recipients[0].recipient);expect(changes.find(c=>c.field==='agent')?.expanded).toBe(true);expect(changes.every(c=>!c.label.includes('recipients.'))).toBe(true);});
it('keeps transaction submission, confirmation, unknown outcomes and finality separate',()=>{expect(historyLabel('submitted')).toContain('awaiting confirmation');expect(historyLabel('confirmed','stopped')).toBe('Spending stopped · Confirmed — awaiting finality');expect(historyLabel('finalized','policy-active')).toBe('Rules applied · Finalized');expect(historyLabel('unknown')).toContain('Outcome unknown');});
