import {it,expect,vi} from 'vitest';
vi.mock('server-only',()=>({}));
import {Wallet,JsonRpcProvider} from 'ethers';
import {resolve} from 'node:path';
import {bootstrapPrivateRules,rulesPrivateConfigSchema} from '../core/rules-bootstrap';
const addresses=Array.from({length:7},()=>Wallet.createRandom().address);
const config={version:1,chainId:4663,account:addresses[0],registry:addresses[1],owner:addresses[2],approver:addresses[3],accountCodeHash:'0x'+'11'.repeat(32),registryCodeHash:'0x'+'22'.repeat(32),journalDirectory:resolve('work/test-journal'),maxFeePerGas:'1000000000',maxGas:'1000000',maxTotalFee:'1000000000000',relayer:{address:addresses[4],keystore:resolve('work/relayer-keystore.json')},agent:{address:addresses[5],keystore:resolve('work/agent-keystore.json')},guardian:{address:addresses[6],keystore:resolve('work/guardian-keystore.json')}};
const env={DRIVEKEY_RULES_CONFIG:resolve('work/rules-config.json'),DRIVEKEY_PRIVATE_COMPANION:'1',ROBINHOOD_RPC_URL:'https://rpc.example.test',DRIVEKEY_AGENT_CREDENTIAL:'a'.repeat(43),DRIVEKEY_OPERATOR_CREDENTIAL:'b'.repeat(43),DRIVEKEY_RELAYER_KEYSTORE_PASSWORD:'test-password-relayer',DRIVEKEY_AGENT_KEYSTORE_PASSWORD:'test-password-agent',DRIVEKEY_GUARDIAN_KEYSTORE_PASSWORD:'test-password-guardian'};
function fixture(){
 const provider={destroy:vi.fn()} as unknown as JsonRpcProvider;
 return {provider:vi.fn(()=>provider),readConfig:vi.fn(async()=>config),signer:vi.fn(async(path:string)=>({getAddress:async()=>[config.relayer,config.agent,config.guardian].find(r=>r.keystore===path)!.address,signTransaction:vi.fn()})),verify:vi.fn(async()=>({approver:async()=>config.approver,agent:async()=>config.agent.address,guardian:async()=>config.guardian.address})) as any,install:vi.fn()};
}
it('leaves ordinary previews unconfigured without reading keys or networking',async()=>{const d=fixture();expect(await bootstrapPrivateRules({},d)).toEqual({configured:false});expect(d.readConfig).not.toHaveBeenCalled();expect(d.provider).not.toHaveBeenCalled();});
it('installs three verified, narrowly scoped executors without signing or sending',async()=>{const d=fixture();expect(await bootstrapPrivateRules(env,d)).toMatchObject({configured:true});const r=d.install.mock.calls[0][0];expect(r.executor.pins.allowedSelectors).toHaveLength(1);expect(r.agentExecutor.pins.allowedSelectors).toHaveLength(2);expect(r.guardianExecutor.pins.allowedSelectors).toHaveLength(1);expect(r.executor.directory).toBe(r.agentExecutor.directory);for(const result of d.signer.mock.results){const signer=await result.value;expect(signer.signTransaction).not.toHaveBeenCalled();}expect(d.verify).toHaveBeenCalledTimes(3);});
it.each([{VERCEL:'1'},{DRIVEKEY_PRIVATE_COMPANION:'0'},{ROBINHOOD_RPC_URL:'http://rpc.example.test'},{DRIVEKEY_OPERATOR_CREDENTIAL:env.DRIVEKEY_AGENT_CREDENTIAL},{DRIVEKEY_AGENT_KEYSTORE_PASSWORD:''}])('rejects unsafe/incomplete environment without installation: %j',async patch=>{const d=fixture();await expect(bootstrapPrivateRules({...env,...patch},d)).rejects.toThrow('did not verify');expect(d.install).not.toHaveBeenCalled();expect(d.signer).not.toHaveBeenCalled();});
it.each([{owner:config.agent.address},{approver:config.guardian.address},{relayer:config.agent},{maxTotalFee:'1000000000000001'},{privateKey:'never-accepted'},{chainId:1}])('rejects aliases, excess fee authority and extra secret fields: %j',patch=>{expect(()=>rulesPrivateConfigSchema.parse({...config,...patch})).toThrow();});
it('rejects wrong deployed roles before unlocking signers',async()=>{const d=fixture();d.verify.mockResolvedValue({approver:async()=>config.owner,agent:async()=>config.agent.address,guardian:async()=>config.guardian.address});await expect(bootstrapPrivateRules(env,d)).rejects.toThrow();expect(d.signer).not.toHaveBeenCalled();expect(d.install).not.toHaveBeenCalled();});
it('rejects a key whose public address differs and disposes the provider',async()=>{const d=fixture();d.signer.mockImplementation(async()=>({getAddress:async()=>config.owner,signTransaction:vi.fn()}));await expect(bootstrapPrivateRules(env,d)).rejects.toThrow();expect(d.install).not.toHaveBeenCalled();expect(d.provider.mock.results[0].value.destroy).toHaveBeenCalled();});
it('sanitizes RPC and decryption errors',async()=>{const d=fixture();d.verify.mockRejectedValue(Error('https://rpc.example.test/secret-key'));await expect(bootstrapPrivateRules(env,d)).rejects.toThrow(/^Private agent companion configuration did not verify\./);expect(d.install).not.toHaveBeenCalled();});
